sample_file: "samples.tsv"
read_file: "reads.tsv"

mito: "MT"
picard: "/work/project/fragencode/tools/multi/picard-tools-2.20.4/picard.jar"
workdir: "/work/project/fragencode/tools/atacseq/fragencode-atacseq-pipeline"

genome:
  bos_taurus:
    /work/project/fragencode/data/species/bos_taurus/UMD3.1.90/bos_taurus.fa
  capra_hircus:
    /work/project/fragencode/data/species/capra_hircus/CHIR_1.0.102/capra_hircus.fa
  gallus_gallus:
    /work/project/fragencode/data/species/gallus_gallus/Gallus_gallus-5.0.90/gallus_gallus.fa
  sus_scrofa:
    /work/project/fragencode/data/species/sus_scrofa/Sscrofa11.1.90/sus_scrofa.fa
