name: atacseq
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python =3.6
  - biopython =1.73
  - snakemake-minimal =5.5.0
  - drmaa =0.7.9
  - pandas =0.23
  - cutadapt =2.1
  - samtools =1.9
  
